# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
 - 'on': ['@all']
   'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/kcrash': '@latest-kf6'
    'frameworks/kio': '@latest-kf6'
    'frameworks/knewstuff': '@latest-kf6'
    'frameworks/kdoctools': '@latest-kf6'
    'frameworks/ktextwidgets': '@latest-kf6'
    'frameworks/ki18n': '@latest-kf6'
    'frameworks/kxmlgui': '@latest-kf6'
    'frameworks/kcoreaddons': '@latest-kf6'

Options:
 require-passing-tests-on: ['@all']
